TejalKhade28/Xecute

README.md

Added all the things that want to add in a readme.md file.
#6

Documentation of README file

---

README.md

Added contributors section in readme

---

index1.html

changed name of heading TO DO APP to XECUTE.

changed name 

---

contact.php
signlog.php
style2.css

- Improved submit button in contact page & added some border radius.
- On signlog.php page changed cursor to pointer for all buttons, initially it was default
- On signlog.php page changed color of click here to blue on hover

Improved Submit button & cursor pointer

---

about.css
about.html

designed footer and added title and subtitle in aboutUs page.

AboutUs Page

---

signlog.php

- Added hover effect on the signin and signup buttons of signlog.php page

Added hover effect on signin/up buttons

---

about.html
contact.php

- Added all the links in footer of contact page and about page
- Added target= _blank so now links will open in new page
Contact page
about page

Added links in footer

---

about.css
contact.php

Changed the background of ContactUs page.

Background Image 

---

index.php

- Instead of images of social icons , I've added actual icons from font awesome and added some styling & color to it.
- Added hover effect on each icons & added target as blank so they open in a new page & also added links
- Instagram
- Twitter
- Facebook

Improved social icons

---

contact.php

added title and sub title to contact.php page.

Contact.php page

---

index1.html

- Changed the names of My task and contact us

Updated index1.html

---

signlog.php

Changed background image of signlog.php

---

signlog.php

- Changed both the subheading in signlog.php page

Updated sub heading in signlog.php page

---

index.php

Updated background of home page

---

contact.css
contact.php

Contact us page icons

---

about.css
contact.php

Removed hover effect from navbar.

Removed hover effect 

---

about.html
contact.php
index.php

Changed the about us icon in all pages

---

about.css
about.html
contact.php

- Changed font-style 
- Improved background image also as background size was not cover

Change font-style of about & contact page

---

signlog.php
style2.css

Changed bg color of sliding panels and buttons

---

index.php

Made buttons of same size on index.php

---

about.css
about.html
contact.css
contact.php
index.php

Made all navbar as same

---

index.php
update.php

Added background image in update.php

---

update.php

Added content in update.php

---

style1.css

Added hover effect in menu of index1.html

---

style1.css

Improved text of index1.html

---

about.css
about.html
contact.php

Added hover effect in the links of footer
Added hover effect on social icons also
_Did changes on both about us & contact us page_

added hover effect in footer

---

update.php

Changed color of buttons in update.php

---

about.css
about.html

Improved cards in about us

---

about.html
contact.php
index.php

- Changed redirection of logout buttons to index1.html in all three navbars of home, about & contact

Added redirection of logout to index1.html

---

update.php

- On hover
- improved input field & text color

Improved button in update.php

---

index1.html

Improved button of index1.html

---

about.html
contact.php

Changed pages name in footer

---

contact.php
style2.css

1. Removed the hover effect.
1. Added border radius to all inputs.

Contact and SignUp page

---

signlog.php

Changed font and added sign up

Changes in text of signlog.php

---

index.php

Improved update/delete buttons in index.php

---

about.css
contact.php
index.php

Added hover effect in navbar
